### ISSUE TITLE
Is anybody interested in Open Firmware port of bare-metal FORTH on nuc970?

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NonOS_BSP#1]
Does anybody think, will it be good to have some interactive shell to experiment with nuc976 hardware directly via UART command line?

* **U-Boot** works well for its narrow goal: bootloader only.
* **Linux** is also great, but it is a full-functional heavy general purpose OS
* **FreeRTOS** is targeted only to run a single specific multitasking application.

Does anybody interested in a mid-level solution, **stays between them**: very light, _low-level but user interactive system_ can be used for experimenting, hardware testing, or automated command processing sent from up level servers via UART, telnet or USB/serial?

I mean [OpenFirmware](https://en.wikipedia.org/wiki/Open_Firmware) port or some primitive FORTH system:
* https://www.youtube.com/watch?v=KvxxAeuhPp0
* http://www.dialectronics.com/Words/OF_Part_I.shtml
* http://www.dialectronics.com/Words/OF_Part_II.shtml
* http://www.dialectronics.com/Words/OF_Part_III.shtml

**Comment by yachen** [comment]
Close this thread because there's no further discussion.
