### ISSUE TITLE
Need some help to port some gdb stub able to work over UART

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NonOS_BSP#2]
I have a preproduction board without JTAG pins routed on PCB, uses nuc906dk61y

Developers use Microchip KSZ8795 switch IC, in a result, I have no Ethernet working, and needs a lot of interactive debugging to fix eth driver to be work with it.

Surprisingly this hardware has very buggy USB, so I ever cannot write into DRAM with NuWriter on my developer workstation, 

The only interface is a serial port, with u-boot preloaded on SPI flash.

Is any manual exists how can I port some gdb stub can be run by u-boot loaded with x/zmodem over the serial line?

**Comment by yachen** [comment]
The JTAG is a standard IEEE 1149.1 interrace. You can find its interface protocol in ARM's ARM926 manual. But in NUC970 series, JTAG interface is disable by default. You'll need to connect with NuWriter or booting successfully from SPI/eMMC/NAND to enable this JTAG interface.

We don't have manual describe the usage of gdb. The usage is the same with other platforms.


Sincerely,

Yi-An Chen

**Comment by ponyatov** [comment]
Anyway I can only run debugger stub/server downloaded by serial line only (I have no working USB BRI on one board, some hw problems maybe, does not the matter).

Many architectures have debug support in hardware, as an example on x86 we have debug registers and exception traps support in hw (some of this mechanics I see in nuc970 manual in residual quantities too). 
* https://en.wikipedia.org/wiki/X86_debug_register

As I can't connect to the JTAG on many boards, the only way I can do is a software-only debug support by gdb stub. GDB stub provides the interface for remote debug over serial UART and follows gdb command protocol by a set of procedures implements breakpoint set/remove, switch on debug trap on every machine command executed, exception traps, etc.

sw GDB stub is not so powerful as hw debug (with breakpoints by variable values watch in realtime, for example), but on many very simple microcontrollers this stub is still usable, and gives minimal stuff for interactive debug.

**Comment by yachen** [comment]
You miss interpret my reply. NUC970 series has HW JTAG. Due to security reason, it's disabled by default. To enable JTAG, the system need to ether
1. Connect with NuWriter successfully, or
2. Find a valid init code in NAND/SPI/eMMC and boot up.

**Comment by ponyatov** [comment]
Oh, it is much much better, it is not a problem to send a few bytes to enable it, but I can't connect anything to the ready board. I'll report later if I found a solution.

**Comment by yachen** [comment]
If you have DEV board in hand (which should be able to connect with PC via USB), you can program a loader image to storage media via NuWriter, and swap the NAND/SPI/eMMC (depend on power on setting option) to the problematic board. The JTAG interface will be enabled after power on.

**Comment by turoksama** [comment]
if he has a nuwriter.
Well, it is too
complicated to make funs of it.

**Comment by yachen** [comment]
NuWriter is a PC tool.  https://github.com/OpenNuvoton/NUC970_NuWriter

**Comment by turoksama** [comment]
I think it needs a hardware to make it work...

**Comment by yachen** [comment]
Close this thread because there's no further discussion.
