### ISSUE TITLE
Totally lack of GNU toolchain support

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NonOS_BSP#3]
Is it real that this BSP lack of GNU toolchain support?

I don't see any Makefile or manual on building bare-metal cross compiler GCC for nuc976.

Maybe other project covers 
* `arm-none-eabi` cross-toolchain build, 
* newlib porting
* using remote `gdb`

with GNU\Linux tools?

**Comment by ponyatov** [comment]
If I want to expand it with GNU, should I use something like `doxygen` for source code documenting?

**Comment by ponyatov** [comment]
What is the right place to put notes on manual cross-compiler build?

**Comment by ponyatov** [comment]
When I use `doxygen`, I have two branches for my project
* `master` holds release version with `docs/` directory (generated .html) right in git repo, and
* `dev` branch holds unstable works, without .html

Then I enable GitHub pages in options, and route it to `master:docs/`

In result, I have public available manual, like https://ponyatov.github.io/nuFORTH/

**Comment by yachen** [comment]
Hi,

Currently we only plan to support Keil develop environment in NUC970 bare bone BSP.
We hold ARM9 BSP in git. But Github is only one of the git server to host BSP. Also we deliver our BSP in zip format. So we'll not rely too much on Github's feature.

Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
I probably know why are you asking about the documents.
We only track the bare bone source code with git. Other documents, including a chm file generated from doxygen comment in drivers, are not hold in git.

**Comment by yachen** [comment]
We're working on GNU tool chain support now. Will push it out once complete. Thanks.
