### ISSUE TITLE
Development with QEMU emulator

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NonOS_BSP#4]
Are any recommends exists on configuring and tips to develop and debug non-OS applications for NUC970 series which can be done simulated under QEMU? https://www.qemu.org

`qemu-system-arm` has full arm926 core simulation, but some peripherals incompatible with say nuc976.

I think it maybe can be useful to have an ability to **run hardware-independent part of the application** without a need to have development board on the table. It can be done **by linking application code with special simulated hardware libraries** replaces nuc976 specific code to generic arm926 and ARM Versatile/PB simulated hardware (maybe other board supported by qemu?).

**Comment by ponyatov** [comment]
I don't say about QEMU patching itself: it is a really big work to write nuc970 emulator into QEMU comparing to my feeling and doubt of how long will be nuc976 in a long-term production and how will be popular products available.

I don't see lite and cheap products on Nuvoton site looks like this board http://www.starterkit.ru/html/index.php?name=shop&op=view&id=141 (besides this board has a few drawbacks thus I don't want to buy it anyway). Maybe something like Raspberry Pi clone produced in mass quantities can do a game, but not a Tomato board with its comparatively high price and lack of AliExpress logistics.

PS: mixing nuc976 with Lattice ICE40 FPGA can make an interesting promo product with reasonable price

**Comment by yachen** [comment]
Close this thread because there's no further discussion.
