### ISSUE TITLE
How to set the scale up/down quality of nuc970 GE2D module?

### ISSUE THREAD

**Issue by ghost** [OpenNuvoton/NUC970_NonOS_BSP#5]
Hi,

Now I'm tyring to sclae down a bmp with nuc972 GE2D module, and it does works, but the quality is not very good. So does anyone know how to set the scale up/down quality of nuc970 GE2D module?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/5708060/55059281-830eef80-50a9-11e9-987f-29fbf81944c2.png)

**Comment by yachen** [comment]
Hi,

The scale up/down quality is not configurable.
Implement scale up/down in application layer with proper filter may give you a better output quality.



Sincerely,

Yi-An Chen
