### ISSUE TITLE
freeRTOS support?

### ISSUE THREAD

**Issue by Tibalt** [OpenNuvoton/NUC970_NonOS_BSP#6]
Hi,
I do not know exactly what NonOS means here. Is there a guide to show how to run nuc972 with NonOS_BSP?

But anyway, my question here is:

Is there an offical support for freertos on nuc972 just like linux?

Regards
Tibalt

**Comment by yachen** [comment]
Hi, 

Non-OS BSP was developed for bare-metal programming and later we added FreeRTOS sample. You can find FreeRTOS project in "SampleCode\FreeRTOS". Attached please find Chinese version Non-OS BSP user manual. Let me know if you prefer English version.

[NUC970 Non-OS BSP User Manual CHT.pdf](https://github.com/OpenNuvoton/NUC970_NonOS_BSP/files/3840884/NUC970.Non-OS.BSP.User.Manual.CHT.pdf)

Sincerely,

Yi-An Chen

**Comment by Tibalt** [comment]
English is better. Thanks!

**Comment by Tibalt** [comment]
By the way, how about ucos?

**Comment by yachen** [comment]
Hi,

Here's English version user manual. And no, we don't support uC/OS-II
[NUC970 Non-OS BSP User Manual EN.pdf](https://github.com/OpenNuvoton/NUC970_NonOS_BSP/files/3844134/NUC970.Non-OS.BSP.User.Manual.EN.pdf)

Sincerely,

Yi-An Chen
