### ISSUE TITLE
Freertos with jpeg problem

### ISSUE THREAD

**Issue by RayzzzzzZ** [OpenNuvoton/NUC970_NonOS_BSP#7]
在Freertos创建了一个任务，在任务中解码jpeg出现了整个任务堵塞，无法成功解码。
解码jpeg的代码放到Freertos开启前就无这个问题，可以正常解出正确数据。有办法解决么？

**Comment by yachen** [comment]
Hi,  JPEG code driver 是使用中斷跳 state. 應該不會堵住. 有環境的話請幫忙看一下堵塞在哪裡.  謝謝.

**Comment by RayzzzzzZ** [comment]
卡在了jpegWait()里面。我试过加大了freertos的任务栈，现象也是一样。

**Comment by yachen** [comment]
Hi, 卡裡面就是JPEG 的中斷處理函數沒進去. 請幫忙看一下是中斷是否有正確打開, 或是有其他優先及更高的中段頻繁發出, 讓JPEG 中斷處理函數無法執行到.

**Comment by RayzzzzzZ** [comment]
你好yachen,中断有正常打开。
jpeg解码中断是先会触发DHE_INTS位（也就是Header Decode Complete Interrupt），
然后触发DEC_INTS位（也就是Decode Complete Interrupt）

然而我现在打印出来只进入了一次DHE_INTS，后面就再也无中断触发了。
是否跑FREERTOS时JPEG解码过程需要点特殊处理?

**Comment by RayzzzzzZ** [comment]
我直接在noos的demo中拿了freertos的demo测试，并且写了一个测试硬解的jpeg的函数。
发现如果硬解jpeg发生在xTaskCreate前，可以正确解出jpeg数据。如果在之后的话就不行，即使不进行任务调度也是如此。

**Comment by yachen** [comment]
造了一個 project 測試, 用 ICE 看已經跑飛了. 懷疑是 memory 分配要整理一下. 還需要點時間 debug.

**Comment by RayzzzzzZ** [comment]
谢谢你的回复
我是去除了JPEG_IOCTL_SET_HEADERDECODE_CALBACKFUN的回调，并且设置JPEG_IOCTL_SET_BITSTREAM_ADDR后，设置JPEG_IOCTL_SET_BITSTREAM_ADDR的输入地址。
目前我这边通过修改可以实现在freertos task中循环不断解码Jpeg，运行了几天暂未出现问题。
具体原因未知，目前认为example中的jpeg测试函数不适应多任务系统。
