### ISSUE TITLE
NUC977 nonos memory performence

### ISSUE THREAD

**Issue by RayzzzzzZ** [OpenNuvoton/NUC970_NonOS_BSP#8]
我想问下裸机开发中全局数组的操作是通过cache操作了么，我发现用全局数组做lvgl7的buffer时帧率非常低，因为lvgl会频繁操作buffer。
我尝试过动态分配0x80000000的虚拟内存，速度会比全局数组更慢。如果全局数组已经是最快的内存操作方式，是否还有其他方法可以加快操作？
十分感谢。

**Comment by yachen** [comment]
Hi, 在有呼叫sysEnableCache() 的情況下, 除非是 bit 31 為 1 的位址, 不然都是通過 cache 操作.  也就是除非特別處理, 變數及堆棧都會進 cache. 請查一下應用是否有透過 sysEnableCache() 開 cache. 另外為了避免 sync 問題, CPU寫 frame buffer 的位址需要把原位址 or bit 31. 像是 LCD 驅動中的操作方式:

`return (uint8_t *)((uint32_t)u8BufPtr | 0x80000000);`

**Comment by RayzzzzzZ** [comment]
你好，代码初始化中确认开了cache，sysEnableCache(CACHE_WRITE_BACK); 看来是已经进入cache了。
我还有另外一个问题，什么情况下操作内存的地址需要把原位址 or bit 31。我这边发现有的代码不把bit31置为1会出现一些奇怪的问题，是否通过cache使用的内存是有大小限制。
针对裸机RTOS开发，我经常涉及到动态分配，如何使用内存是最可靠的？

**Comment by yachen** [comment]
Hi, 有DMA 介入的都需要把位址 or bit 31, 例如給網口, USB, 顯示, SD 用的記憶體. 不然可能 CPU寫了, 但還沒刷出 cache, DMA 就來存取. 或是 DMA 寫了, cache 不知道. 整塊 DDR 空間都可以設定成 cacheable 或 non-cacheable 的屬性, 端看 bit 31 設置. 
動態分配要小心跑一陣子後出線內存碎片問題. 至於記憶體使用, 跟有沒有帶作業系統相同, 沒有 DMA 介入的就全部使用 cacheable 就好.
