### ISSUE TITLE
is  i2s' mclk fixed at 256fs?

### ISSUE THREAD

**Issue by chandong83** [OpenNuvoton/NUC970_NonOS_BSP#9]
Hi,

is the mclk of i2s fixed at 256fs?

i want to use i2s' mclk with 384fs.

if i change mclk(384fs) the DMA doesn't work, is there any way?

thank you

**Comment by yachen** [comment]
Are you using Linux or Non-OS system?

**Comment by chandong83** [comment]
Hi, @yachen 
i'm using Linux. but i'm referencing the Non-OS code.
and i'm changing from 256 fs 16-bit to 384 fs 24-bit.
and now I solved the clock problem. but still 24-bit I2S mode does not work.
thank you.
